### ISSUE TITLE
Make SDL2 on by default in cmake-eclipse-linux-profile.sh

### ISSUE THREAD

**Issue by shmerl** [OpenTechEngine/OpenTechBFG#139]
SDL 1.2 is already obsolete and SDL 2 is universally available. You should make SDL 2 a default in all scripts.

**Comment by damiel** [comment]
Done with this commit: https://github.com/OpenTechEngine/OpenTechBFG/commit/e07cdce127e8f0acb15416d4f3802d7cf23240da
