### ISSUE TITLE
Import base assets from d3-base-assets project, enhance if needed

### ISSUE THREAD

**Issue by DanielGibson** [OpenTechEngine/OpenTechBFG#44]
https://github.com/DanielGibson/d3-base-assets

So we can at least load a simple level without any proprietary d3bfg assets.

While creating proper entity .def files takes long, at least func_* are done and I started creating stubs for the others that have the entity name and "spawnclass" (or, if none, "inherits") + information on whether it's an entity with a fixed size or not (editor_mins/editor_maxs set to vectors or "?").

The assets contain a simple box level, we just need to make sure it loads properly and that it's wired to the menu.

**Comment by BielBdeLuna** [comment]
aren't those assets the ones in the assets branch?

**Comment by DanielGibson** [comment]
yeah, but we need to merge that to master *and* I added some stuff in d3-base-assets recently, so it needs updating.

Also: Making sure the demo level works etc.

**Comment by DanielGibson** [comment]
I forked the cegui_layout_upd_assets branch from cegui_layout and added the relevant assets from d3-base-assets + some from the old assets branch (and I merged some entity definitions from kordex into d3-base-assets before).

the demo level (crappy testmap) indeed works.

**Comment by DanielGibson** [comment]
it's imported, the box level is wired to the menu and we have stubs for all entities and even proper definitions for many of them, so I guess this is done.
