### ISSUE TITLE
Using dmap or map arguments crashes OpenTechEngine.exe

### ISSUE THREAD

**Issue by Yetta1** [OpenTechEngine/OpenTechBFG#48]
OpenTechEngine crashes right after 'dmap" command writes .proc file, using dmap in DarkRadiant seems to give the same crash result after using "map" to load the map.

**Comment by DanielGibson** [comment]
not enough information

**Comment by Yetta1** [comment]
The program locks up then stops working after running dmap demo.map, the last few lines readable in the console while frozen is:

-----WriteOutputFile-----
writing maps/demo.proc
0 total shadow triangles
0 total shadow verts
------------------------------
 1 seconds for dmap
Opening IP socket: localhost: 27015

Then the crash occurs

Using the dmap command in DarkRadiant's console creates a successful build and write out all the files needed for the map, however using "map demo.map" in OpenTechEngine crashes the program immediately.

I've managed to get OpenTechEngine to work in the Doom3BFG folder, however I can't load the demo.map or any of Doom3BFG's maps, as it's looking for resources related to flash and xbox/ps3 controllers., which halts the map load.

Is there a console command to log console message output?

**Comment by BielBdeLuna** [comment]
out of curiosity, why are you running dmap in darkradiant?

I see that "dmap" works both in RBDoom3BFG and in OTE, but "map" in RBDooom3BFG sometimes segfaults when loading the map, while in OTE it has never segfaulted on loading the map yet.

have you tried to dmap your map in RBDoom3BFG and try to play it there?

**Comment by Yetta1** [comment]
@BielBdeLuna Sometimes when saving the map and running dmap in the game it wouldn't have saved changes to the brushes of the map. So the old brush layout shows, but the collision is set to the new layout. Running dmap in radiant seems to fix that.

**Comment by Yetta1** [comment]
@DanielGibson Map load seems to fail when engine looks for "WEAPON_IRONSIGHT" in the weapon_kick.def script.

**Comment by DanielGibson** [comment]
This problem should be fixed in the branch I told you to use (with the 
base/ dir of that branch, not of d3bfg).

**Comment by Yetta1** [comment]
@DanielGibson I'm using that branch. I looked at the definition script, there were no lines containing weapon_ironsight. Should I look into the other branches for the .def containing the code?

I managed to open my map on RBDoom3BFG after running dmap on Vanilla Doom 3, however there seems to be a scaling issue, the map seems smaller or it's the player entity that is way bigger.

**Comment by DanielGibson** [comment]
it's not in the def, it's in the script.

`weapon_base` in base/script/weapon_base.script  should contain `boolean WEAPON_IRONSIGHT;`.  
`weapon_kick` in weapon_kick.script derives from that.

for me that fixed crashes related to WEAPON_IRONSIGHT.

**Comment by Yetta1** [comment]
@DanielGibson The file did not contain that line of code, I added it in and tried loading the map in OTE, it crashed.

**Comment by DanielGibson** [comment]
then you're using the wrong branch anyway.

**Comment by Yetta1** [comment]
@DanielGibson I'm using cegui_layout_upd_assets

**Comment by Yetta1** [comment]
Maybe there was a syncing problem from github

**Comment by DanielGibson** [comment]
I don't know how well that works around half the world, but do you want me to look at it via VNC (tightvnc?), maybe together with teamspeak or mumble?

**Comment by Yetta1** [comment]
@DanielGibson I tried the script from githubs app, the engine gave this error:

QA Timing INIT: 000001ms
BFG $Id: 3a05baaf07de033974095ff42eaf7b9e6c08377f $.1401 win-x86 Jul 20 2015 21:49:23
2494 MHz generic CPU with SSE & SSE2
Winsock Initialized
Found interface: {60EBFC69-A26D-4C59-BC83-361A3ACB4C75} Atheros L2 Fast Ethernet 10/100Base-T Controller - 192.168.1.8/255.255.255.0
Sys_InitNetworking: adding loopback interface
------ Initializing File System ------
Current search path:
C:\Users\Tiaan\Saved Games\id Software\RBDOOM 3 BFG/base
E:\Games\OTEtest\Release/base
file system initialized.
--------------------------------------
----- Initializing Decls -----
------------------------------
Couldn't open journal files
execing default.cfg
execing D3BFGConfig.cfg
couldn't exec autoexec.cfg
----- R_InitOpenGL -----
Initializing OpenGL subsystem with multisamples:0 stereo:0 fullscreen:0
...registered window class
...registered fake window class
Using GLEW 1.10.0
...created window @ 0,0 (1296x759)
Initializing OpenGL driver
...creating GL context: created OpenGL 3.2 context
succeeded
...making context current: succeeded
Using GLEW 1.10.0

------- Input Initialization -------
Initializing DirectInput...
mouse: DirectInput initialized.
keyboard: DirectInput initialized.
------------------------------------
OpenGL Version  : 4.5
OpenGL Vendor   : NVIDIA Corporation
OpenGL Renderer : GeForce GT 630/PCIe/SSE2
OpenGL GLSL     : 4.5
   maxTextureAnisotropy: 16.000000
...using GL_EXT_texture_lod_bias
X..GL_GREMEDY_string_marker not found
...using GL_EXT_framebuffer_object
...using GL_EXT_framebuffer_blit
----- Initializing Render Shaders -----
----- Initializing Sound System ------
  0: Speakers (Turtle Beach PLa Headset)
     2 channels, 48000 Hz
     Front Left and Front Right
     Default Console Device, Multimedia Device, Communications Device, and Game Device
  1: SPDIF Interface (TX0) (VIA HD Audio(Win8.1)(Compatible))
     2 channels, 48000 Hz
     Front Left and Front Right
  2: Speakers (VIA HD Audio(Win8.1)(Compatible))
     2 channels, 48000 Hz
     Front Left and Front Right
Using device 0
sound system initialized.
--------------------------------------
------- Initializing renderSystem --------
WARNING: Couldn't load image: textures/loadingicon2 : textures/loadingicon2#__0200
WARNING: Couldn't load image: textures/loadingicon3 : textures/loadingicon3#__0200
Updating texture filter parameters.
renderSystem initialized.
--------------------------------------
WARNING: Couldn't load image: guis/assets/splash/legal_english : guis/assets/splash/legal_english#__0200
Skipping Intro Videos!
Reading strings/english.lang as ASCII
11 strings read
WARNING: Couldn't load image: newfonts//48 : newfonts//48#__0400
WARNING: Couldn't load image: ui/assets/guicursor_hand_cross : ui/assets/guicursor_hand_cross#__0200
WARNING: Couldn't load image: ui/assets/guicursor_hand_circle : ui/assets/guicursor_hand_circle#__0200
WARNING: Couldn't load image: ui/assets/guicursor_hand_square : ui/assets/guicursor_hand_square#__0200
WARNING: Couldn't load image: ui/assets/guicursor_hand_triangle : ui/assets/guicursor_hand_triangle#__0200
WARNING: Couldn't load image: ui/assets/guicursor_hand_a : ui/assets/guicursor_hand_a#__0200
WARNING: Couldn't load image: ui/assets/guicursor_hand_b : ui/assets/guicursor_hand_b#__0200
WARNING: Couldn't load image: ui/assets/guicursor_hand_x : ui/assets/guicursor_hand_x#__0200
WARNING: Couldn't load image: ui/assets/guicursor_hand_y : ui/assets/guicursor_hand_y#__0200
--------- Initializing Game ----------
gamename: baseDOOM-1
gamedate: Jul 20 2015
Initializing event system
...535 event definitions
Initializing class hierarchy
...158 classes, 496480 bytes for event callbacks
Initializing scripts
--------- Game Map Shutdown ----------
--------------------------------------
idMenuHandler_Shell::ActivateMenu 0
********************
ERROR: Error: file script\weapon_base.script, line 33: weapon_base::NetCatchup redeclared


********************
Error during initialization
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): success
...deleting GL context: success
...releasing DC: success
...destroying window

**Comment by Yetta1** [comment]
I have teamspeak. Going to be away from the pc for 10-20 minutes.

**Comment by DanielGibson** [comment]
then also install tightvnc server so I can look onto your PC to see what happens and tell me when you're ready.  
Should be easier to sort things out that way :)

**Comment by Yetta1** [comment]
Ok i'm back. Got teamspeak and VNC server running.

**Comment by DanielGibson** [comment]
maybe get into the #iodoom3 irc chan on freenode to discuss which TS server to use etc

**Comment by BielBdeLuna** [comment]
scripts are not yet done, I'm working on it, currently I'm working on monsters AI

**Comment by Yetta1** [comment]
Thank you Daniel! OTE is running without any issues running dmap, can mod the map and dmap while running the engine.

**Comment by Yetta1** [comment]
![gkmcazc](https://cloud.githubusercontent.com/assets/8399958/8833838/259d443a-30b1-11e5-9ea9-f1832cd7993d.jpg)

**Comment by DanielGibson** [comment]
ok, I guess we can close this one then :)
