### ISSUE TITLE
Deployment is painful

### ISSUE THREAD

**Issue by kortemik** [OpenTechEngine/OpenTechBFG#56]
On Windows built dll-libraries end up into build/bin/, theOpenTechEngine.exe into build/ and base is at the repo root. Running freshly built engine is pretty painful as it requires moving things around.

This can be fixed. One option is to add -basedir command line option or use symbolic links or have some other way of combining the deployment ready for one-click solution.

The issue is also in Linux but should not be that hard to solve as symbolic links are native and so on.

**Comment by DanielGibson** [comment]
yeah, I'd suggest making sure the OpenTechEngine.exe ends up in build/bin/ as well.

regarding the commandline option, it may even exist already as a cvar, we'll have to look into it

maybe we could generate a small .bat file from cmake that calls the .exe with the right basedir to make things even easier. (possibly a shell script for linux that does the same)

**Comment by DanielGibson** [comment]
half of this is fixed: you run OpenTechEngine with `+set fs_basepath ..` or similar to set the path where `base/` and `demo/` are in.

the "making sure the OpenTechEngine.exe ends up in build/bin/ as well" is still missing, @kortemik, could you look at that? you're more familiar with the cmake stuff.

**Comment by BielBdeLuna** [comment]
can dll or the external libraries be embedded within the executable?

**Comment by DanielGibson** [comment]
not sure if cegui supports static linking well.

**Comment by kortemik** [comment]
fixed for windows, all is now in /build/bin

static linking is supported but not preferred

**Comment by BielBdeLuna** [comment]
static linking is putting all the libraries within a single file?

**Comment by kortemik** [comment]
It's a way to do that, yes. Of course one could just zip but would that be
any good? :D

**Comment by BielBdeLuna** [comment]
idk , what do you mean for "just zip"?

**Comment by kortemik** [comment]
Like compress them into archive, it was more of a joke for a comment.

**Comment by BielBdeLuna** [comment]
ok
