### ISSUE TITLE
Namespace consistency

### ISSUE THREAD

**Issue by kortemik** [OpenTechEngine/OpenTechBFG#57]
Everything should be in the BFG namespace (or a subnamespace of it). so idCEGUI should be BFG::idCEGUI, CEGUIConsole should be BFG::CEGUIConsole and BFG::CEGUIMenu..

**Comment by DanielGibson** [comment]
Another small style-related thing I noticed in the CEGUIMenu::MenuInterface: I think we should stick to the Doom3 standard of naming methods in UpperCamelCase (`Init()` instead of `init()`, `SetVisible()` instead of `setVisible()` etc)

**Comment by BielBdeLuna** [comment]
no need to keep the "id" for every name, in quake 4 sdk it helps to find the rv in every function Raven did, it helps to separate their functions from id's.

I myself always do my functions with "bl" so it's easier to read the code in the future.

**Comment by DanielGibson** [comment]
not sure if having lots of different prefixes is a good idea..
if you're looking for e.g. a classname, now you can look for id<whateveryou're searching for> - a lot more painful to also look for (or try in autocompleteion) bl<whatever>, dg<whatever>, ...

**Comment by BielBdeLuna** [comment]
well if you search for "whatever" in the IDE you will find both so no problem here, try to port your code changes from code base to code base and you will see it easily if we don't stick with the "id"

**Comment by Yetta1** [comment]
Or just ot<whatever>

**Comment by DanielGibson** [comment]
fixed via #60
