### ISSUE TITLE
OTE release binary needed.

### ISSUE THREAD

**Issue by Yetta1** [OpenTechEngine/OpenTechBFG#74]
I'm having issues building with Eclipse and VS 2015 is still a no go, i'll have to download VS 2013 again. Could any of you upload a release binary to work from? My current binary is broken and the debug version doesn't wantto work for me.

**Comment by kortemik** [comment]
https://sourceforge.net/projects/opentechengine/files/snapshot/Windows/MinGW/

MinGW builds should work just fine without any microsoft tools.

**Comment by Yetta1** [comment]
@kortemik Thank you kortemik, will try later, currently on working through linux.

**Comment by Yetta1** [comment]
@kortemik Works great, thank you!
