### ISSUE TITLE
mouse wheel causes engine to abort because no weapons defined. 

### ISSUE THREAD

**Issue by kortemik** [OpenTechEngine/OpenTechBFG#78]
OpenTechEngine: /home/kordex/code/OpenTechBFG/neo/d3xp/Player.cpp:5697: void BFG::idPlayer::Weapon_Combat(): Assertion `idealWeapon.Get() >= 0' failed.
signal caught: Aborted
si_code -6
Trying to exit gracefully..
session->GetSaveGameManager().CancelToTerminate();
soundSystem->StopAllSounds();
Stop(); 

I am all open to suggestions what to do with this. I think it would be better to just replace the assert with warning.

**Comment by BielBdeLuna** [comment]
yeah a warning should be fine

**Comment by Yetta1** [comment]
I still have to complete the weapon model animation and texturing. I'll create a quick dirty texture and upload the blend. Someone will have to get it into the engine. Kind of swamped with other work.

**Comment by BielBdeLuna** [comment]
supply the *.blend and we'll create the md5animation and mesh files :+1:
