### ISSUE TITLE
Mouse issues

### ISSUE THREAD

**Issue by Yetta1** [OpenTechEngine/OpenTechBFG#81]
Built binaries under release for 32-bit and 64-bit versions. There is an issue with the mouse not moving the player, it works in the menu however, except when pressing the escape in the menu, the mouse pointer vanished, but shows activity when hovered over the buttons.

Here is another issue for the mouse on a older 64-bit from a clone around 3 months ago, it is related to the mouse-wheel crashing the game. Here is a screenshot of the error message.

![mousedown_error](https://cloud.githubusercontent.com/assets/8399958/10564947/498f52ee-75c5-11e5-94fc-d103f8524606.png)

**Comment by Yetta1** [comment]
The no mouse movement issue only seems to occur on the 32-bit release build, the 64-bit works. Going to rebuild the 32-bit to see if there may have been a compiling issue.

**Comment by Yetta1** [comment]
Rebuilt the 32-bit binary, the mouse movement works again. However the mousewheel crash still occurs on the latest github clone.

**Comment by kortemik** [comment]
Yes that's because we don't have more than one weapon enabled, that assert
should be changed as a warning not assert.

**Comment by DanielGibson** [comment]
hopefully this is properly fixed now
