### ISSUE TITLE
glsl shader compilation fails on radeon hd 7850 using mesa

### ISSUE THREAD

**Issue by damiel** [OpenTechEngine/OpenTechBFG#83]
Hello,

while attempting to start the engine, the startup fails, here's the paste of the output: https://bpaste.net/show/befbb061fa2b .

I am on linux, running kernel version 4.4.6 and mesa 11.2.2/llvm 3.8, and compiled the engine from the master branch. Here is the output of glxinfo: https://bpaste.net/show/8f2e58323afc

kordex/(kortemik?) pointed me on irc to the following issue for rbdoom-3-bfg:

https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/252

It basically boils down to this comment: https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/252#issuecomment-157086271

I'll give it a shot and report back with results.

EDIT: The engine starts just fine with the applied changes.

**Comment by BielBdeLuna** [comment]
what have you changed?

**Comment by damiel** [comment]
I added 

"precision lowp sampler2D;\n"
"precision lowp sampler2DShadow;\n"
"precision lowp sampler2DArray;\n"
"precision lowp sampler2DArrayShadow;\n"
"precision lowp samplerCube;\n"
"precision lowp samplerCubeShadow;\n"
"precision lowp sampler3D;\n"

to /renderer/RenderProgs_GLSL.cpp

**Comment by BielBdeLuna** [comment]
ok, so it's the same solution I did.

in case you don't know it, if you want to know the OpenGL core and compat versions you can do the following:
`glxinfo | grep OpenGL`
there core profile version is easily detailed, and compat is just the other version of OpenGL you get there, (most of the time they match but sometimes they don't, in that situation the higher version is core)
