### ISSUE TITLE
We should look into integrating HDR and other enhancements from RBDOOM3-BFG.

### ISSUE THREAD

**Issue by TheNorseHorse** [OpenTechEngine/OpenTechBFG#93]
They've added HDR, and are experimenting with SMAA. I think we could use these things in OTE. Adding PBR will be even faster, as the experimental BRDF has also been integrated.

**Comment by BielBdeLuna** [comment]
the experimental BRDF it's still a stub though

**Comment by damiel** [comment]
I started porting HDR/SMAA/SSAO/SSGI to ote, but i am not sure when i am done with it and even(choking a bit with merging changes from the embeded shaders) when i am done with it i still think we need a proper settings menu, to give an easy accessible way to tweak those settings.

**Comment by DanielGibson** [comment]
I don't think this has high priority. Let RBD3BFG get it stable and possibly faster first, in the end merging shouldn't be too hard.

We still have lots of things to do here, like
* improving the main menu
* a HUD (probably using CEGUI)
* fixing the CEGUI-based console
* maybe integrate a crash handler like breakpad
* improving ingame tools/adding more (see imgui-tools branch)
* finishing entity definitions
* example player model, example weapons, items, monsters
* example level(s) (and maybe textures) showing existing features

**Comment by BielBdeLuna** [comment]
@DanielGibson what do you think of this? https://github.com/OpenTechEngine/Discussions/issues/39

**Comment by damiel** [comment]
I am done now with porting but i wont do a pull request just now because there are still a couple of things left that need fixing/adjustment. But i would appreciate if someone could test my branch and give feedback.

https://github.com/damiel/OpenTechBFG/tree/renderupdate

**Comment by damiel** [comment]
The bigger bunch of the graphical enhancements is already ported, only thing left is the pbr related work which i currently have in a branch. There is still a lot work left to do but i suggest we discuss this in our "forum". I am closing this issue for said reason.
